<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Address' => '',
    'Assignment' => '',
    'Auth Key' => '',
    'Current' => '',
    'Disable' => '',
    'Enter your password' => '',
    'Enter your verifyCode' => '',
    'Incorrect username or password.' => '',
    'Last Login At' => '',
    'Name' => '',
    'Please enter username.' => '',
    'Sign in' => '',
    'Slug' => '',
    'Create Admin' => '创建管理员',
    'Delete Admin' => '删除管理员',
    'Manage Admin' => '管理员管理',
    'Password Hash' => '密码哈希',
    'Update Admin' => '修改管理员',
    'Username' => '用户名',
];
