<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear' => '',
    'Close Popup' => '',
    'Collapse Menu' => '',
    'Loading...' => '',
    'Logout' => '',
    'Manage Center' => '',
    'Refresh' => '',
    'Shortcut' => '',
    'Voice command failed' => '',
    'Warning! This will reset all your widget settings.' => '',
    'You can improve your security further after logging out by closing this opened browser' => '',
    'Cancel Search' => '取消搜索',
    'Full Screen' => '全屏',
    'Search' => '搜索',
    'Sign Out' => '退出登录',
];
