<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Loop detected.' => '',
    'Add subMenu' => '添加子菜单',
    'Create Menu' => '创建菜单',
    'Data' => '附加数据',
    'Delete Menu' => '删除菜单',
    'Icon' => '图标',
    'Manage Menu' => '管理菜单',
    'Menu Name' => '菜单名称',
    'Parent Menu' => '父菜单',
    'Route' => '路由',
    'Sort' => '排序',
    'Update Menu' => '修改菜单',
    'Visible' => '是否可见',
];
